name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: get version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .
      - name: Print the version
        run: echo "The version was ${{ steps.get-version.outputs.version }}"
      - name: Configure .env file
        run: |
          touch .env
          echo PROD_SLACK_APP_TOKEN=$PROD_SLACK_APP_TOKEN >> .env
          echo PROD_CLERK_SECRET_KEY=$PROD_CLERK_SECRET_KEY >> .env
          echo PROD_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$PROD_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY >> .env
          echo PROD_DATABASE_URL=$PROD_DATABASE_URL >> .env
          echo PROD_SLACK_CLIENT_ID=$PROD_SLACK_CLIENT_ID >> .env
          echo PROD_SLACK_CLIENT_SECRET=$PROD_SLACK_CLIENT_SECRET >> .env
          echo PROD_SLACK_CODE=$PROD_SLACK_CODE >> .env
          echo PROD_COMMUNICATION_TOKEN=$PROD_COMMUNICATION_TOKEN >> .env
          echo NEXT_PUBLIC_CLERK_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_SIGN_IN_URL >> .env
          echo NEXT_PUBLIC_CLERK_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_SIGN_UP_URL >> .env
          echo NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL >> .env
          echo NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL >> .env
          echo SLACK_REDIRECT_URI=$SLACK_REDIRECT_URI >> .env
        shell: bash
        env:
          PROD_SLACK_APP_TOKEN: ${{secrets.PROD_SLACK_APP_TOKEN}}
          PROD_CLERK_SECRET_KEY: ${{secrets.PROD_CLERK_SECRET_KEY}}
          PROD_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.PROD_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
          PROD_DATABASE_URL: ${{secrets.PROD_DATABASE_URL}}
          PROD_SLACK_CLIENT_ID: ${{secrets.PROD_SLACK_CLIENT_ID}}
          PROD_SLACK_CLIENT_SECRET: ${{secrets.PROD_SLACK_CLIENT_SECRET}}
          PROD_SLACK_CODE: ${{secrets.PROD_SLACK_CODE}}
          PROD_COMMUNICATION_TOKEN: ${{secrets.PROD_COMMUNICATION_TOKEN}}
          NEXT_PUBLIC_CLERK_SIGN_IN_URL: /auth/sign-in
          NEXT_PUBLIC_CLERK_SIGN_UP_URL: /auth/sign-in
          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /
          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /
          SLACK_REDIRECT_URI: https://standup-bot.com/api/i
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: standupbotcom
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            standupbotcom/ssb:latest
            standupbotcom/ssb:${{ steps.get-version.outputs.version }}
            standupbotcom/ssb:${{ github.sha }}
      - name: applying new image on prod
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd slack-standup-bot
            ggl
            ./start.sh
